import type { CliIo } from "../types/cli.js";
import { loadHarnessConfig, HARNESS_CONFIG_FILE } from "../core/config-service.js";
import { listActivePlans, hasActivePlans } from "../core/task-service.js";
import { getStatus } from "../core/status-service.js";
import { join } from "node:path";

export async function runStartCommand(cwd: string, io: CliIo): Promise<number> {
  const configResult = await loadHarnessConfigSafe(cwd);

  if (!configResult.success) {
    await io.write(configResult.error);
    await io.write("");
    await io.write("Run 'harness init' first to create a harness baseline.");
    return 1;
  }

  const config = configResult.config;
  const projectName = config.projectName;

  // Get current status
  const status = await getStatus(cwd);
  const activePlans = await listActivePlans(cwd);
  const hasPlans = await hasActivePlans(cwd);

  // Build the startup prompt
  const prompt = buildStartupPrompt({
    projectName,
    status,
    activePlans,
    hasPlans,
    configPath: join(cwd, HARNESS_CONFIG_FILE),
  });

  await io.write(prompt);
  return 0;
}

interface StartupPromptContext {
  projectName: string;
  status: {
    missingManagedFiles: string[];
    driftedManagedFiles: string[];
  };
  activePlans: string[];
  hasPlans: boolean;
  configPath: string;
}

function buildStartupPrompt(context: StartupPromptContext): string {
  const lines: string[] = [
    `# Harness Activation: ${context.projectName}`,
    "",
    "You are now operating in **harness orchestrator mode** for this repository.",
    "",
    "---",
    "",
    "## First-Turn Actions",
    "",
    "1. Read these files in order:",
    "   - `HARNESS_BOOTSTRAP.md` — activation protocol and delegation rules",
    "   - `.codex/config.toml` — subagent limits",
    "   - `.codex/agents/*.toml` — role capabilities",
    "   - `ARCHITECTURE.md` — system boundaries",
    "   - `docs/index.md` — documentation routing",
    "",
    "2. Acknowledge you are in orchestrator mode and ready to coordinate.",
    "",
    "---",
  ];

  // Add status section
  lines.push("");
  lines.push("## Current Repository Status");
  lines.push("");

  if (context.status.missingManagedFiles.length > 0) {
    lines.push("**Missing harness files:**");
    for (const file of context.status.missingManagedFiles) {
      lines.push(`- ${file}`);
    }
    lines.push("");
  }

  if (context.status.driftedManagedFiles.length > 0) {
    lines.push("**Drifted files (may need attention):**");
    for (const file of context.status.driftedManagedFiles) {
      lines.push(`- ${file}`);
    }
    lines.push("");
  }

  // Add active plans section
  if (context.hasPlans) {
    lines.push("**Active execution plans:**");
    for (const plan of context.activePlans) {
      lines.push(`- docs/exec-plans/active/${plan}.md`);
    }
    lines.push("");
  } else {
    lines.push("**Active execution plans:** None");
    lines.push("");
  }

  // Add quick reference
  lines.push("---");
  lines.push("");
  lines.push("## Quick Reference");
  lines.push("");
  lines.push("| Task Type | Your Action |");
  lines.push("|-----------|-------------|");
  lines.push("| explain | Respond directly |");
  lines.push("| analyze | Delegate to planner/reviewer |");
  lines.push("| plan | Delegate to planner |");
  lines.push("| implement | Delegate to builder |");
  lines.push("| debug | Sequential: planner → builder → tester |");
  lines.push("| review | Delegate to reviewer |");
  lines.push("| verify | Delegate to tester |");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("*This prompt was generated by `harness start`. Use it to activate harness mode when starting a new Codex session in this repository.*");

  return lines.join("\n");
}

async function loadHarnessConfigSafe(cwd: string): Promise<
  | { success: true; config: Awaited<ReturnType<typeof loadHarnessConfig>> }
  | { success: false; error: string }
> {
  try {
    const config = await loadHarnessConfig(cwd);
    return { success: true, config };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { success: false, error: message };
  }
}
