import type { HarnessConfig } from "../types/harness.js";

const ENRICHABLE_DOC_PATHS = [
  "HARNESS_BOOTSTRAP.md",
  "AGENTS.override.md",
  "ARCHITECTURE.md",
  "docs/index.md",
  "docs/DESIGN.md",
  "docs/FRONTEND.md",
  "docs/PLANS.md",
  "docs/PRODUCT_SENSE.md",
  "docs/QUALITY_SCORE.md",
  "docs/RELIABILITY.md",
  "docs/SECURITY.md",
  "docs/design-docs/index.md",
  "docs/product-specs/index.md",
  "docs/references/index.md",
] as const;

export function buildCodexEnrichPrompt(config: HarnessConfig): string {
  return [
    `You are enriching the harness runtime for "${config.projectName}".`,
    `Preferred collaboration language: ${config.language}.`,
    "",
    "== BOOTSTRAP OBJECTIVE ==",
    "",
    "Your primary goal is to bootstrap this repository so that Codex",
    "operates in harness orchestrator mode by default, not as a general-purpose assistant.",
    "",
    "The enriched docs should enable:",
    "1. Stable activation of orchestrator mode on session start",
    "2. Clear delegation rules and role triggers",
    "3. Runtime-aware behavior (routing-first, implementation-by-delegation)",
    "",
    "== WRITE SCOPE ==",
    "",
    ...ENRICHABLE_DOC_PATHS.map((path) => `- You may create or update \`${path}\`.`),
    "- Do not rewrite `docs/design-docs/template.md`, `docs/product-specs/template.md`, or `docs/exec-plans/template.md` into project-specific content.",
    "",
    "== HARDEST CONSTRAINTS ==",
    "",
    "1. DO NOT modify application code, tests, dependencies, lockfiles, CI, or build configuration.",
    "2. Base every statement on repository evidence. If something is unclear, mark it as an explicit open question or assumption.",
    "3. Keep guidance concrete and useful for future Codex sessions.",
    "4. Preserve any high-signal existing content instead of replacing it with generic boilerplate.",
    "5. Stay conservative: document what exists, do not invent patterns you cannot verify.",
    "",
    "== REQUIRED OUTCOMES ==",
    "",
    "HARNESS_BOOTSTRAP.md must:",
    "- Define main thread identity as harness orchestrator",
    "- Specify first-turn action protocol",
    "- Include task classification rules (explain/analyze/plan/implement/debug/review/verify)",
    "- Include complexity assessment (trivial/moderate/complex)",
    "- Include delegation rules (when to delegate vs direct action)",
    "- Include light task exemption rules",
    "",
    "AGENTS.override.md must:",
    "- Include bootstrap protocol at the top",
    "- Explain document lookup order (starting with HARNESS_BOOTSTRAP.md)",
    "- Define role boundaries for orchestrator, planner, builder, reviewer, tester",
    "- Include delegation trigger rules and role trigger rules",
    "- Make it serve as both collaboration guide and bootstrap trigger",
    "",
    "ARCHITECTURE.md must:",
    "- Summarize real module boundaries from the codebase",
    "- Document runtime shape and important technical constraints",
    "- Capture actual system patterns, not ideal ones",
    "",
    "docs/index.md must:",
    "- Route readers to the right source-of-truth files",
    "- Reference HARNESS_BOOTSTRAP.md as the first read",
    "",
    "The topical docs must:",
    "- Capture repo-specific product, design, quality, reliability, and security context where evidence exists",
    "- Mark unknowns explicitly instead of inventing details",
    "",
    "== PROCESS ==",
    "",
    "1. Inspect codebase, package manifests, config files, and existing docs before editing.",
    "2. Focus on enabling orchestrator mode activation and delegation behavior.",
    "3. Prefer concise, factual writing over placeholders.",
    "4. Leave template files intact for future task-specific docs.",
    "",
    "== RUNTIME ACTIVATION CHECK ==",
    "",
    "After completing enrichment, verify:",
    "- HARNESS_BOOTSTRAP.md exists and contains first-turn protocol",
    "- AGENTS.override.md references HARNESS_BOOTSTRAP.md first in read order",
    "- The bootstrap protocol defines task classification and delegation rules",
    "- Orchestrator role is clearly distinguished from implementation roles",
    "",
    "If these are not satisfied, the repository will not reliably enter harness mode on Codex startup.",
  ].join("\n");
}
